// THIS FILE IS AUTOMATICALLY GENERATED
// DON'T CHANGE IT IN ORDER TO MAKE IT PROPERLY WORK!
export default defineNuxtPlugin(() => ({
  provide: {
    iconsPath: '/Users/ramel9/work/softonix/nuxt-boilerplate/assets/icons',
    icons: { eyeTest: 'eye-test' }
  }
}))
