// THIS FILE IS AUTOMATICALLY GENERATED
// DON'T CHANGE IT IN ORDER TO MAKE IT PROPERLY WORK!
export default defineNuxtPlugin(() => ({
  provide: {
    routeNames: {
      index: 'index',
      contacts: 'contacts',
      about: 'about',
      aboutSoftonix: 'about-softonix'
    }
  }
}))
