import { writeFileSync } from 'fs'
import { join as pathJoin } from 'pathe'
import { inspect as utilInspect } from 'util'
import { NuxtPage } from '@nuxt/schema'
import { camelCase } from 'change-case'

const routeNames: Record<string, string> = {}
// Parses pages folder and recursively ignores all files placed in /components dirs.
function parseRoutes (routes: NuxtPage[]) {
  for (let i = routes.length - 1; i >= 0; i--) {
    const route = routes[i]
    if (['/_components/', '.ts'].some(ext => route.file.includes(ext))) {
      routes.splice(i, 1)
    } else {
      routeNames[camelCase(route.name as string)] = route.name as string
    }

    parseRoutes(route.children || [])
  }
}

// Builds routes and generates route names
function buildRouter (routes: NuxtPage[]) {
  console.info('Generating routes')
  parseRoutes(routes)
  writeFileSync(
    pathJoin(__dirname, 'route-names.plugin.ts'),
    String('// THIS FILE IS AUTOMATICALLY GENERATED\n')
      .concat('// DON\'T CHANGE IT IN ORDER TO MAKE IT PROPERLY WORK!\n')
      .concat(`export default defineNuxtPlugin(() => (${utilInspect({ provide: { routeNames } })}))`)
      .concat('\n')
  )
  console.info('Warming up vite clients...')
}

export {
  buildRouter
}
